apiVersion: v1
kind: ConfigMap
metadata:
  name: harbor-ca
  namespace: kube-system
data:
  harbor-ca.crt: |+
    -----BEGIN CERTIFICATE-----
    MIID2jCCAsKgAwIBAgIQNLqrsV+V4ahO/hTPnm3kGTANBgkqhkiG9w0BAQsFADBf
    MRIwEAYKCZImiZPyLGQBGRYCYnIxEzARBgoJkiaJk/IsZAEZFgNjb20xGzAZBgoJ
    kiaJk/IsZAEZFgtjcmVkaWNpdHJ1czEXMBUGA1UEAxMOQ1JFRElDSVRSVVMtQ0Ew
    HhcNMTcwNzIyMTIzNjE1WhcNNDcwNzIyMTI0NjE1WjBfMRIwEAYKCZImiZPyLGQB
    GRYCYnIxEzARBgoJkiaJk/IsZAEZFgNjb20xGzAZBgoJkiaJk/IsZAEZFgtjcmVk
    aWNpdHJ1czEXMBUGA1UEAxMOQ1JFRElDSVRSVVMtQ0EwggEiMA0GCSqGSIb3DQEB
    AQUAA4IBDwAwggEKAoIBAQCiD4Y7AD2ENUPcmzB+Zeot3a/hM34ZD9qiukmQkH5r
    QWeQ0J/4038QuOJHFKaNfIuZnHD5TgdYYo4sYEfhxuPAqIgMA5i7CvsnyNFVhr15
    TjhqIJatCpeKYzd9kWekiHsSS10mI/80qfom1+lg36oeiB6bk0IaBzBp8Skw1y9Q
    vvu/VWgLPwlMZZJeql0xRHb0ovpemrHkl+ZYuCT4Ng0QkPgeNU6yy2ZPJPeILRCQ
    h2T6Tx9C7F7q2SezO1KN8z9f91iavYkeulvH1E8i6BFEVmy4Qffm99GOZgJxB8gd
    rV4/BYpWXlQVOZu7/+8OOzZwc/FBO5xa9y8VDFf12RJTAgMBAAGjgZEwgY4wEwYJ
    KwYBBAGCNxQCBAYeBABDAEEwDgYDVR0PAQH/BAQDAgGGMA8GA1UdEwEB/wQFMAMB
    Af8wHQYDVR0OBBYEFElB59N3TDDn142c9hPIn7ayyVUXMBIGCSsGAQQBgjcVAQQF
    AgMCAAIwIwYJKwYBBAGCNxUCBBYEFHJnLYou6sJGXS352Ag3TzY2cnWlMA0GCSqG
    SIb3DQEBCwUAA4IBAQBay/tzLIKROZNDB38yLHlwHmgLCZAbSr/8397c36p0D3hj
    +3yLBW/QTLMXRQA0qCVeQoPCd0cWKWxyxqbHG/8AUfVbs0HnJ26kueShbkSnukOl
    0SneTYpEZDmJ7VEndUXOpC9C0kv7qVoWQ/l7f+e9As+dSJc5EBaPVQrB1xSyUm3j
    TpvA+H3cDDTwXCmAryCy1ARv7AOJbYs/3INfQWsynI+yBBiVjKbpR7wHBB/PZvXx
    X0cmeTqwhhivnSh64O9r8FbfiqW7bOOkgzmJqdCP6RGP5QpnZMJxgm0hObrZ4Irk
    EjgUBzArTyyUwhwSv9a4Q1u3w4xpJYctjil9KLIo
    -----END CERTIFICATE-----

---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  namespace: kube-system
  name: node-install-certs
  labels:
    k8s-app: node-install-certs
spec:
  selector:
    matchLabels:
      k8s-app: node-install-certs
  template:
    metadata:
      labels:
        k8s-app: node-install-certs
    spec:
      hostPID: true
      hostNetwork: true
      initContainers:
      - name: init-node
        command: [ "nsenter" ]
        args:
        - "--mount=/proc/1/ns/mnt"
        - "--"
        - "sh"
        - "-c"
        - >
          echo "$TRUSTED_CERT" > /etc/ssl/certs/harbor-ca.crt && systemctl restart containerd && echo "10.5.1.185  3188-dc01-00273.credicitrus.com.br  3188-dc01-00273" >> /etc/hosts
        image: debian
        env:
        - name: TRUSTED_CERT
          valueFrom:
            configMapKeyRef:
              name: harbor-ca
              key: harbor-ca.crt
        securityContext:
          privileged: true
      containers:
      - name: wait
        image: k8s.gcr.io/pause:3.1
